
export const services = [
  {
    id: "01",
    title: "ALUMINIUM AND FURNITURE SERVICES",
    description: "High-quality aluminium fabrication and furniture solutions. We provide durable, stylish, and customized designs to enhance your home or office space.",
    src: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop",
    bgColor: "bg-white",
    className: "text-xl md:text-2xl whitespace-nowrap",
    wide: true,
  },
  {
    id: "02",
    title: "MKSUKO ATTA",
    description: "Premium quality fresh Chakki Atta. Made from the finest grains to ensure soft and healthy rotis for your family. Experience the taste of purity.",
    src: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=800&auto=format&fit=crop",
    bgColor: "bg-white",
    className: "text-xl md:text-2xl whitespace-nowrap",
  },
  {
    id: "03",
    title: "MKSUKO WATER",
    description: "Pure and refreshing mineral water. Processed with advanced filtration technology to ensure safety and hydration in every drop.",
    src: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?q=80&w=800&auto=format&fit=crop",
    bgColor: "bg-lime-400",
    className: "text-xl md:text-2xl whitespace-nowrap",
  },
  {
    id: "04",
    title: "Social Media Management",
    description: "Elevate your presence on social platforms. From content creation to strategy and analytics, we help you connect with your audience and build a loyal community.",
    src: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=800&auto=format&fit=crop",
    bgColor: "bg-white",
    className: "text-xl md:text-2xl whitespace-nowrap",
    wide: true,
  },
  {
    id: "05",
    title: "Photography Services",
    description: "Tell your story through stunning visuals. Whether it's product shots, portraits, or event photography, we capture moments that define your brand.",
    src: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop",
    bgColor: "bg-white",
    className: "text-xl md:text-2xl whitespace-nowrap",
  },
];
